version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bealy_tt_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./back
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: bealy_tt_db
      DB_USER: root
      DB_PASS: root
      DB_HOST: db
      PORT: 8080
      JWT_SECRET: "hackernewssecretkey123456"
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    networks:
      - app_network

  frontend:
    build: ./front
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8080"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
