# Utilisation de l'image Node.js
FROM node:20

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers package.json et package-lock.json
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du code source
COPY . .

# Construction de l'application Next.js
RUN npm run build

# Exposition du port Next.js
EXPOSE 3000

# Commande de démarrage
CMD ["npm", "start"]